// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXWkhp1YAQDMjc86XG35HHT3uvYgNoQi8',
    appId: '1:1047803086118:web:861b765f6fd84330086de7',
    messagingSenderId: '1047803086118',
    projectId: 'hawing-app',
    authDomain: 'hawing-app.firebaseapp.com',
    storageBucket: 'hawing-app.firebasestorage.app',
    measurementId: 'G-T81SRBTHK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0fwSDl3i9A668PJvgOZlcdIxyHzT42hk',
    appId: '1:1047803086118:android:bc57944dc572cbbb086de7',
    messagingSenderId: '1047803086118',
    projectId: 'hawing-app',
    storageBucket: 'hawing-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGvpXuK1a9oWZ6gZJFPZIf71GHy2yfKhI',
    appId: '1:1047803086118:ios:f9bcd3e08cac628b086de7',
    messagingSenderId: '1047803086118',
    projectId: 'hawing-app',
    storageBucket: 'hawing-app.firebasestorage.app',
    iosBundleId: 'com.example.hwingExchange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGvpXuK1a9oWZ6gZJFPZIf71GHy2yfKhI',
    appId: '1:1047803086118:ios:f9bcd3e08cac628b086de7',
    messagingSenderId: '1047803086118',
    projectId: 'hawing-app',
    storageBucket: 'hawing-app.firebasestorage.app',
    iosBundleId: 'com.example.hwingExchange',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXWkhp1YAQDMjc86XG35HHT3uvYgNoQi8',
    appId: '1:1047803086118:web:dedddc8166c519f8086de7',
    messagingSenderId: '1047803086118',
    projectId: 'hawing-app',
    authDomain: 'hawing-app.firebaseapp.com',
    storageBucket: 'hawing-app.firebasestorage.app',
    measurementId: 'G-E5E7E7711X',
  );
}
